# Generated by Django 2.1.7 on 2019-04-04 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
