# Generated by Django 2.1.7 on 2019-04-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to22', '0004_item_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
