# Generated by Django 2.1.7 on 2019-04-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to22', '0005_auto_20190407_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='picture',
            new_name='URL',
        ),
    ]
