"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6w(i=()y0!&l)3zb&avp)yi1@)pc44u+=q5@@gv@z85sm4!6i+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'pwa',
    'to22',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,  'templates'),
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/app/db/db.sqlite3'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# Parse database configuration from $DATABASE_URL
import dj_database_url
db_from_env = dj_database_url.config()
DATABASES['default'].update(db_from_env)

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow all host headers
ALLOWED_HOSTS = ['*','akademia-django.herokuapp.com']

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'akademia.kyoto@gmail.com'
EMAIL_HOST_PASSWORD = 'umekizemi-aka'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

"""
EMAIL_HOST = 'smtp.lolipop.jp'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'info@akademia.tech'
EMAIL_HOST_PASSWORD = 'Denden11_thisistest'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'info@akademia.tech'
"""

# Static asset configuration
STATIC_ROOT = '/app/static/'

STATICFILES_DIRS = (
    #os.path.join(BASE_DIR, 'static'),
    '/app/to22/static/',
    '/app/media/'
)

#STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_URL = '/to22/'
LOGIN_REDIRECT_URL = '/to22/'
LOGOUT_REDIRECT_URL = '/to22/'

try:
    from .local_settings import *
except ImportError:
    pass

AUTH_USER_MODEL = 'to22.User'

PWA_APP_NAME = 'To22'
PWA_APP_DESCRIPTION = "To22 app description"
PWA_APP_START_URL = '/to22/'

PWA_SERVICE_WORKER_PATH = "https://s3-ap-northeast-1.amazonaws.com/to22-media/media/to22/serviceworker.js"

PWA_APP_ICONS = [
        {
            'src': 'https://s3-ap-northeast-1.amazonaws.com/to22-media/static/img/%E5%AE%B6_1.png',
            'sizes': '160x160'
            }
        ]
PWA_APP_SPLASH_SCREEN = [
        {
            'src': 'https://s3-ap-northeast-1.amazonaws.com/to22-media/static/img/%E5%AE%B6_.png',
            'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
            }
        ]

MEDIA_ROOT = '/app/'
MEDIA_URL = '/to22-media/'

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#
# AWS_ACCESS_KEY_ID = 'AKIAQCZ4VWYSS3T2PQUJ'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_STORAGE_BUCKET_NAME = 'to22-media'
#
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# AWS_S3_OBJECT_PARAMETERS = {
#     'CacheControl': 'max-age=86400',  # 1日はそのキャッシュを使う
# }
#
# AWS_LOCATION = 'static'
#
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIR = (os.path.join(BASE_DIR, 'static'),)

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

AUTHENTICATION_BACKENDS = [
    'social_core.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
]
SOCIAL_AUTH_TWITTER_KEY = 'cZxsIdrlqQKe3AJ4PAp6qs1Mj'
SOCIAL_AUTH_TWITTER_SECRET = 'mlDQYrCgLskAONm95RlA725Yy9Y0XpzBPIXpzOcccvWu5cKD6O'
#SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/to22/'# ログイン後のリダイレクト先

#TEST_RUNNER = 'django_heroku.HerokuDiscoverRunner'
#django_heroku.settings(locals())
